function(cacheset Name Value)
	get_property(V_ADVANCED CACHE "${Name}" PROPERTY ADVANCED)
	get_property(V_TYPE CACHE "${Name}" PROPERTY TYPE)
	get_property(V_HELPSTRING CACHE "${Name}" PROPERTY HELPSTRING)
	set(${Name} ${Value} CACHE ${V_TYPE} ${V_HELPSTRING} FORCE)
	if(${V_ADVANCED})
		mark_as_advanced(FORCE ${Name})
	endif()
endfunction()

function(cacheclear Name)
	get_property(V_ADVANCED CACHE "${Name}" PROPERTY ADVANCED)
	get_property(V_TYPE CACHE "${Name}" PROPERTY TYPE)
	get_property(V_HELPSTRING CACHE "${Name}" PROPERTY HELPSTRING)
	set(${Name} 0 CACHE ${V_TYPE} ${V_HELPSTRING} FORCE)
	if(${V_ADVANCED})
		mark_as_advanced(FORCE ${Name})
	endif()	
endfunction()